#Deployment 오브젝트의 API 버젼
apiVersion: apps/v1
#생성할 오브젝트 type
kind: Deployment
metadata:
  #오브젝트 이름
  name: catalog-service
  #deployment를 "app=catalog-service"로 레이블
  labels:
    app: catalog-service
spec:
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
        labels:
            app: catalog-service
    spec:
      containers:
        - name: catalog-service
          #사용할 이미지, tag 없으니 latest로 사용
          image: catalog-service
          #쿠버네티스에게 로컬에 이미자가 없으면 pull 하도록
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            #Paketo 빌드팩이 사용할 환경변수, 스레드 개수
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            #스프링 datasource 환경변수, db
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://polar-postgres/polardb_catalog
            # 스프링 프로필 "testdata" 활성화
            - name: SPRING_PROFILES_ACTIVE
              value: testdata